stages:
    - buid
    # - deploy

variables:
    HOSTNAME: "tracker"

build-dev-image:
    stage: buid
    before_script:
        - docker info
    script: 
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME .
    artifacts:
        paths:
        - build
    tags:
        - cgaspard-runner
    only:
        - develop

build-master-image:
    stage: buid
    before_script:
        - docker info
    script: 
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY/$CI_PROJECT_PATH:latest .
    artifacts:
        paths:
        - build
    tags:
        - cgaspard-runner
    only:
        - master

deploy-dev:
    stage: deploy
    before_script:
        - docker info
    script: 
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    tags:
        - cgaspard-runner
    only:
        - develop
    when: always

deploy-master:
    stage: deploy
    before_script:
        - docker info
    script: 
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
    tags:
        - cgaspard-runner
    only:
        - master
    when: manual
