stages:
    - build
    - deploy

variables:
    HOSTNAME: "tracker"

build-dev-image:
    stage: build
    before_script:
        - docker info
    script: 
        - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME .
    tags:
        - swarm-node-01
    only:
        - develop

build-master-image:
    stage: build
    before_script:
        - docker info
    script: 
        - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -t $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest .
    tags:
        - swarm-node-01
    only:
        - master

deploy-dev:
    stage: deploy
    before_script:
        - docker info
    script: 
        - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    tags:
        - swarm-node-01
    only:
        - develop
    when: always
    dependencies:
        - build-dev-image

deploy-master:
    stage: deploy
    before_script:
        - docker info
    script: 
        - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
        - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest
    tags:
        - swarm-node-01
    only:
        - master
    when: manual
    dependencies:
        - build-master-image
