stages:
    - build
    - deploy

variables:
    HOSTNAME: "tracker"

build-dev-image:
    stage: build
    before_script:
        - docker info
    script: 
        - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME .
    artifacts:
        paths:
        - build
    tags:
        - cgaspard-runner
    only:
        - develop

build-master-image:
    stage: build
    before_script:
        - docker info
    script: 
        - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -t $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest .
    artifacts:
        paths:
        - build
    tags:
        - cgaspard-runner
    only:
        - master

deploy-dev:
    stage: deploy
    before_script:
        - docker info
    script: 
        - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    tags:
        - cgaspard-runner
    only:
        - develop
    when: always

deploy-master:
    stage: deploy
    before_script:
        - docker info
    script: 
        - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
        - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest
    tags:
        - cgaspard-runner
    only:
        - master
    when: manual
